name: package

on:
  push:
    branches:
      - master
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"

      - name: Build
        shell: bash
        run: |
          git submodule update --init --depth 1
          sh scripts/clone_emsdk.sh
          source emsdk/emsdk_env.sh

          python3 build.py

      - uses: actions/upload-artifact@v4
        with:
          name: EffekseerForWebGL
          path: Release
